name: Update repo stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  update_data:
    name: Update repo stats
    runs-on: ubuntu-latest
    steps:
      - name: Query GitHub GraphQL API
        id: GH_GQL_QUERY
        uses: octokit/graphql-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query repo_stats($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                stargazerCount
                pullRequests(states: OPEN) {
                  totalCount
                }
                issues(states: OPEN) {
                  totalCount
                }
              }
            }
          owner: ${{ secrets.REPOSITORY_OWNER }}
          repo: ${{ secrets.REPOSITORY_NAME }}
      - name: Log results
        run: |
          echo "Issue count: ${{ fromJSON(steps.GH_GQL_QUERY.outputs.data).repository.issues.totalCount }}"
          echo "Pull request count: ${{ fromJSON(steps.GH_GQL_QUERY.outputs.data).repository.pullRequests.totalCount }}"
          echo "Stargazer count: ${{ fromJSON(steps.GH_GQL_QUERY.outputs.data).repository.stargazerCount }}"
